<div id="logo"><span class="sna">sna</span><span class="api">api</span></div>
<div id="catch-phrase"><i>simple</i> <b>API search</b></div>

<div id="small-logo" style="display:none"><span class="sna">sna</span><span class="api">api</span></div>
<div id="search">
  <form action="post" onsubmit="return false">
    <input type="text" class="text" size="50" name="search" autocomplete="off" />
    <div class="dropdown" style="display:none"></div>
    <div class="filters" style="display:none"></div>
  </form>
</div>

<div id="result" style="display:none"></div>
<div id="external_page" style="display:none"></div>

<?php
$this->headLink()->appendStylesheet('/css/index.css');

if ('production' == $this->env) {
  $this->inlineScript()->appendFile('/js/snap/core.js');
  $this->inlineScript()->appendFile('/js/snap/ui.js');
} else {
  $this->inlineScript()->appendFile('/js/snap/core/snap.js');

  $this->inlineScript()->appendFile('/js/snap/ui/ghost-input.js');
  $this->inlineScript()->appendFile('/js/snap/ui/type-ahead.js');
}

$this->inlineScript()->appendFile('/js/page/dashboard.js');
