<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link rel="shortcut icon" href="/favicon.ico" mce_href="/favicon.ico" />
  <?= $this->headTitle() ?>
  <? if( APPLICATION_ENVIRONMENT == 'development' ) { ?>
  <style type="text/css">
  .devonly {
    border: 1px solid #ccc;
    background-color: #ff0;
    padding: 0.2em;
  }
  </style>
  <? } ?>
<?php  // These are in a reverse order of importance because we're prepending.
  $this->headLink()->prependStylesheet('/css/common.css');
  $this->headLink()->prependStylesheet('/css/global.css'); ?>
<?= $this->headLink() ?>
<?= $this->headScript() ?>
</head>
<body>

<div id="page">

<div id="actions">
  <ul>
    <? if( Zend_Auth::getInstance()->hasIdentity() ) { ?>
    <li><a href="/profile">Profile</a></li>
    <li><a href="/logout">Log out</a></li>
    <? } else { ?>
      <li><a href="/login" title="Log in to snaapi with OpenID or a snaapi account">Log in</a></li>
      <li><a href="/signup" title="Or log in using Google, myOpenID, or a number of other services">Sign up</a></li>
    <? } ?>
  </ul>
</div>

<div id="content">

<div id="logo"><a href="/"><span class="sna">sna</span><span class="api">api</span></a></div>

<?= $this->layout()->content ?>
</div>

<div id="spacer"></div>

</div>

<div id="footer">
  <div class="wrapper">
    <div class="links">
    <ul>
      <li><a href="/">Home</a></li>
      <li><a href="/contact">Contact</a></li>
      <li><a href="/about">About</a></li>
    </ul>
    </div>
    <div class="copyright">©2009 snaapi</div>
  </div>
</div>

<?php  // These are in a reverse order of importance because we're prepending.
  global $REVISIONS;
  $this->inlineScript()->prependFile('/js/static/revisions.js?'.$REVISIONS['ALL']);
  $this->inlineScript()->prependFile('/js/jquery.js');
  if( Zend_Auth::getInstance()->hasIdentity() ) {
    $identity = Zend_Auth::getInstance()->getIdentity();
    $this->inlineScript()->prependScript('window.user_id = '.$identity['id'].';');
  }
?>
<?= $this->inlineScript() ?>

</body>
</html>
