<?php $this->headLink()->appendStylesheet('/css/server_error.css') ?>

<div class="server_error">
<h1>Pardon our dust! Here's what we know about what happened:</h1> 
<h2><?= $this->message ?></h2>

<? if ('development' == $this->env): ?> 
    <h3>Exception information:</h3> 
    <p> 
        <b>Message:</b> <?= $this->exception->getMessage() ?> 
    </p> 

    <h3>Stack trace:</h3> 
    <pre><?= $this->exception->getTraceAsString() ?></pre> 

    <h3>Request Parameters:</h3> 
    <pre><? var_dump($this->request->getParams()) ?></pre> 
<? endif ?>
</div>