<?php $this->headLink()->appendStylesheet('/css/welcome.css') ?>
<div class="info_box"><div class="header">what is snaapi?</div><div class="body trim">
  <p>snaapi is designed for one task: <b>looking up APIs</b>. It's been a side project of Jeff's
    since the beginning of March 2009 because of frustrations from working with the iPhone SDK.</p>
  <p>Jeff writes all of the spiders and scrapers, manages the back-end and the front-end code, and
    every now and then tries his hands at improving the design.</p>
  <p>If you want to talk to Jeff, you can dash over to the <a href="/contact">contact</a>
    section.</p>
  <p>Or you can check out his <a href="http://thejefffiles.com/">musings</a>.</p>
</div></div>

<div class="info_box"><div class="header">design iterations</div><div class="body">
  <div class="version">First iteration: early March, 2009</div>
  <div class="considerations">The emphasis on the first design was the search bar. It was placed
    smack dab in the middle of the screen at the center of focus. This gave a very Google-esque
    feel to the design.</div>
  <a href="/gfx/design1_main.png" title="The home page"><img src="/gfx/design1_main.gif" alt="Design #1: Home page"></a>
  <a href="/gfx/design1_search.png" title="Searching for 'width'"><img src="/gfx/design1_search.gif" alt="Design #1: Search"></a>
  <a href="/gfx/design1_frame.png" title="Viewing a reference page"><img src="/gfx/design1_frame.gif" alt="Design #1: Frame"></a>
  <div class="version">Second iteration: mid March, 2009</div>
  <div class="considerations"><p>After letting people play with the first design, it became clear that
    people weren't really sure how to use it. Filters were hard to see/find, and the original filter
    renderer was fairly rudimentary. There was also a <i>lot</i> of wasted space.</p>
  <p><img src="/gfx/design1_filter.png" alt="Design #1: Filters"></p>
  <p>After carefully considering the design, this new design was created to place more immediate
    emphasis on the content and to make filters easier to find and use.</p>
  <p><img src="/gfx/design2_filter.png" alt="Design #2: Filters"></p></div>
  <a href="/gfx/design2_main.png" title="The home page"><img src="/gfx/design2_main.gif" alt="Design #2: Home page"></a>
  <a href="/gfx/design2_search.png" title="Searching for 'width'"><img src="/gfx/design2_search.gif" alt="Design #2: Search"></a>
  <a href="/gfx/design2_frame.png" title="Viewing a reference page"><img src="/gfx/design2_frame.gif" alt="Design #2: Frame"></a>
</div></div>

<div class="the-team">
  <h1>The Team</h1>
  <div>Yeah, it's just one guy.</div>
  <img src="/gfx/jeff.jpg" width="400" height="300" alt="Jeff Verkoeyen" />
  <div class="name">Jeff Verkoeyen</div>
</div>
