<?php $this->headLink()->appendStylesheet('/css/welcome.css') ?>
<div class="info_box"><div class="header">what is snaapi?</div><div class="body">
  <p>snaapi is designed for one task: <b>looking up APIs</b>. It's been a side project of Jeff's
    since the beginning of March 2009 because of frustrations from working with the iPhone SDK.</p>
  <p>Jeff writes all of the spiders and scrapers, manages the back-end and the front-end code, and
    every now and then tries his hands at improving the design.</p>
  <p>If you want to yell and scream at Jeff, you can dash over to the <a href="/contact">contact</a>
    section.</p>
  <p>Or you can check out his <a href="http://thejefffiles.com/">musings</a>.</p>
</div></div>

<div class="the-team">
  <h1>The Team</h1>
  <div>Yeah, it's just one guy.</div>
  <img src="/gfx/jeff.jpg" width="400" height="300" alt="Jeff Verkoeyen" />
  <div class="name">Jeff Verkoeyen</div>
</div>
