<?php $this->headLink()->appendStylesheet('/css/welcome.css') ?>
<div class="info_box"><div class="header">what we do</div><div class="body">
  <p>We make API lookups <b>fast</b> and <b>easy</b>. Instead of trying to replace Google or any individual
    site's search functionality, we provide an <b>index of API functions</b> paired with
    <b>user-submitted examples</b>.</p>
</div></div>

<div class="the-team">
  <h1>The Team</h1>
  <img src="/gfx/jeff.jpg" width="400" height="300" alt="Jeff Verkoeyen" />
  <div class="name">Jeff Verkoeyen</div>
</div>
