<?php $this->headLink()->appendStylesheet('/css/contact.css') ?>
<h1>Contact the snaapi team</h1>

<div class="contact">
  <div class="row">
    <span class="name">Jeff Verkoeyen</span>
  </div>
  <div class="row">
    <span class="position">Founder</span>
  </div>
  <div class="row">
    <span class="title">Email:</span>
    <span class="email">jverkoey at gmail</span>
  </div>
  <div class="row">
    <span class="title">Twitter:</span>
    <span class="twitter"><a href="http://twitter.com/featherless" title="Follow Jeff on twitter">featherless</a></span>
  </div>
</div>