<div id="listing">
<div class="function"><a href="/twitter/create">create</a></div>
<div class="function"><a href="/twitter/create">create</a></div>
<div class="function"><a href="/twitter/create">create</a></div>
<div class="function"><a href="/twitter/destroy">destroy</a></div>
<div class="function"><a href="/twitter/destroy">destroy</a></div>
<div class="function"><a href="/twitter/destroy">destroy</a></div>
<div class="function"><a href="/twitter/destroy">destroy</a></div>
<div class="function"><a href="/twitter/destroy">destroy</a></div>
<div class="function"><a href="/twitter/direct_messages">direct_messages</a></div>
<div class="function"><a href="/twitter/end_session">end_session</a></div>
<div class="function"><a href="/twitter/exists">exists</a></div>
<div class="function"><a href="/twitter/favorites">favorites</a></div>
<div class="function"><a href="/twitter/follow">follow</a></div>
<div class="function"><a href="/twitter/followers">followers</a></div>
<div class="function"><a href="/twitter/friends">friends</a></div>
<div class="function"><a href="/twitter/friends_timeline">friends_timeline</a></div>
<div class="function"><a href="/twitter/ids (followers)">ids (followers)</a></div>
<div class="function"><a href="/twitter/ids (friends)">ids (friends)</a></div>
<div class="function"><a href="/twitter/leave">leave</a></div>
<div class="function"><a href="/twitter/new">new</a></div>
<div class="function"><a href="/twitter/public_timeline">public_timeline</a></div>
<div class="function"><a href="/twitter/rate_limit_status">rate_limit_status</a></div>
<div class="function"><a href="/twitter/replies">replies</a></div>
<div class="function"><a href="/twitter/sent">sent</a></div>
<div class="function"><a href="/twitter/show">show</a></div>
<div class="function"><a href="/twitter/show">show</a></div>
<div class="function"><a href="/twitter/test">test</a></div>
<div class="function"><a href="/twitter/update">update</a></div>
<div class="function"><a href="/twitter/update_delivery_service">update_delivery_service</a></div>
<div class="function"><a href="/twitter/update_location">update_location</a></div>
<div class="function"><a href="/twitter/update_profile">update_profile</a></div>
<div class="function"><a href="/twitter/update_profile_background_image">update_profile_background_image</a></div>
<div class="function"><a href="/twitter/update_profile_colors">update_profile_colors</a></div>
<div class="function"><a href="/twitter/update_profile_image">update_profile_image</a></div>
<div class="function"><a href="/twitter/user_timeline">user_timeline</a></div>
<div class="function"><a href="/twitter/verify_credentials">verify_credentials</a></div>
</div>
